AWSTemplateFormatVersion: "2010-09-09"
Description: Aws-quick-start demo application infrastruture
Resources:
  Repository:
    Type: AWS::CodeCommit::Repository
    Properties: 
      Code: 
        S3:
          # todo make it publicly available
          Bucket: aws-quick-start
          Key: seed.zip
      RepositoryDescription: This is a aws-quick-start demo app repository
      RepositoryName: aws-quick-start-app
  StaticWebResources:
    Type: AWS::S3::Bucket
  