AWSTemplateFormatVersion: "2010-09-09"
Description: Aws-quick-start demo application infrastruture
Resources:

  Repository:
    Type: AWS::CodeCommit::Repository
    Properties: 
      Code: 
        S3:
          # todo make it publicly available
          Bucket: aws-quick-start
          Key: seed.zip
      RepositoryDescription: This is a aws-quick-start demo app repository
      RepositoryName: aws-quick-start-app
  
  StaticWebResourcesBucket:
    Type: AWS::S3::Bucket

  ArtifactStoresBucket:
    Type: AWS::S3::Bucket
  
  # See https://docs.aws.amazon.com/codepipeline/latest/userguide/how-to-custom-role.html
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: aws-quick-start-builder-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - codecommit:CancelUploadArchive
                  - codecommit:GetBranch
                  - codecommit:GetCommit
                  - codecommit:GetUploadArchiveStatus
                  - codecommit:UploadArchive
                Resource:
                  Fn::GetAtt: [ Repository, Arn ]
              - Effect: Allow
                Action:
                  - s3:*
                Resource: 
                  - !Sub ${ArtifactStoresBucket.Arn}/*
                  - !Sub ${StaticWebResourcesBucket.Arn}/*

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties: 
      Name: aws-quick-start
      ArtifactStore:
        Type: S3 
        Location:
          Ref: ArtifactStoresBucket 
      RoleArn: 
        Fn::GetAtt: [ CodePipelineServiceRole, Arn ]
      Stages: 
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId: 
                Category: Source 
                Owner: AWS 
                Version: 1 
                Provider: CodeCommit
              Configuration:
                BranchName: master
                RepositoryName:
                  Fn::GetAtt: [ Repository, Name ]
              OutputArtifacts: 
                - Name: SourceOutput 
        - Name: Deploy
          Actions:
            - Name: DeployAction
              InputArtifacts: 
                - Name: SourceOutput
              ActionTypeId: 
                Category: Deploy 
                Owner: AWS 
                Version: 1 
                Provider: S3
              Configuration:
                BucketName: 
                  Ref: StaticWebResourcesBucket
                Extract: true
